# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  agentic_harness:
    taskfile: agentic_harness/Taskfile.yml
    dir: agentic_harness
  local_models:
    taskfile: local_models/Taskfile.yml
    dir: local_models
  computer_controller:
    taskfile: computer_controller/Taskfile.yml
    dir: computer_controller

tasks:
  run_harness:
    desc: Run the agentic harness
    cmds:
      - task: local_models:run_gemma4_server
      - task: agentic_harness:run
      - task: local_models:stop_gemma4_server
  integration_test:
    desc: Test the agentic harness
    cmds:
      - task: local_models:run_gemma4_server
      - task: agentic_harness:full_test
      - task: local_models:stop_gemma4_server
  unit_test:
    desc: Test the agentic harness and computer controller
    deps:
      - agentic_harness:unit_test
      - computer_controller:test
  build:
    desc: Builds agentic harness and computer controller
    deps:
      - unit_test
      - computer_controller:build
      - agentic_harness:build
  generate_proto:
    desc: Generate protobuf stubs
    run: once
    sources:
      - 'computer_api/**/*.proto'
      - buf.yaml
      - buf.gen.yaml
      - buf.lock
    generates:
      - 'computer_controller/gen/**/*'
      - 'agentic_harness/src/gen/**/*'
    cmds:
      - buf dep update
      - buf lint
      - buf generate

  build_container_images:
    desc: Builds the container images
    deps:
      - build
      - computer_controller:build_container_images