# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  agentic_harness:
    taskfile: 'Taskfile.bun.yml'
  computer_controller:
    taskfile: apps/computer_controller/Taskfile.yml
    dir: apps/computer_controller

tasks:
  unit_test:
    desc: Test the agentic harness and computer controller
    deps:
      - agentic_harness:unit_test
      - computer_controller:test
  build:
    desc: Builds agentic harness and computer controller
    deps:
      - unit_test
      - computer_controller:build
      - agentic_harness:build

  generate_proto:
    desc: Generate protobuf stubs
    run: once
    sources:
      - 'apps/computer_api/**/*.proto'
      - buf.yaml
      - buf.gen.yaml
      - buf.lock
    generates:
      - 'apps/computer_controller/gen/**/*'
      - 'packages/core/src/gen/**/*'
    cmds:
      - buf dep update
      - buf lint
      - buf generate

  build_container_images:
    desc: Builds the container images
    deps:
      - build
      - computer_controller:build_container_images
      - agentic_harness:build_container_images