# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  build:
    desc: Build the golang project
    cmds:
      - go build ./...
  test:
    desc: Run tests
    cmds:
      - go test ./...
  run:
    desc: Run the application
    cmds:
      - go run ./...
