# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  build:
    desc: Build the API Gateway binary
    run: once
    sources:
      - '**/*.go'
      - go.mod
      - go.sum
    generates:
      - bin/gateway
    cmds:
      - go fmt ./...
      - go mod tidy
      - CGO_ENABLED=0 go build -v -ldflags="-s -w" -o bin/gateway ./cmd/gateway

  test:
    desc: Run unit tests for API Gateway
    run: once
    sources:
      - '**/*.go'
      - go.mod
      - go.sum
    cmds:
      - go test -v ./...

  run:
    desc: Run the API Gateway locally
    cmds:
      - go run ./cmd/gateway

  build_container_image:
    desc: Build API Gateway container image
    deps:
      - build
      - test
    cmds:
      - docker build -f docker/Dockerfile -t api-gateway:latest .

  build_container_images:
    desc: Build all container images for API Gateway
    deps:
      - task: build_container_image

